### ISSUE TITLE
補齊翻譯內容

### ISSUE THREAD

**Issue by vios10009** [benlisquare/stable-diffusion-webui-localization-zh_TW#1]
我有一份自己整理過的翻譯內容[stable-diffusion-webui-localization-zh_TW](https://github.com/vios10009/stable-diffusion-webui-localization-zh_TW)

參考[stable-diffusion-webui-localization-zh_CN](https://github.com/dtlnor/stable-diffusion-webui-localization-zh_CN)

這邊可以把沒補上的部分補齊，然後我就會關閉那個分支了，我只是搬運工

**Comment by benlisquare** [comment]
OK，我這星期什麽時候不忙我就把沒補上的merge一下。

**Comment by vios10009** [comment]
> 好吧，我這週什麼時候不忙我沒補上的合併。

OK，我丟上合併請求了 #2
有空再合併就好
