### ISSUE TITLE
如何一打開就是繁體字?

### ISSUE THREAD

**Issue by seq2193** [benlisquare/stable-diffusion-webui-localization-zh_TW#20]
在kaggle 上面如何設定一打開就是繁體字? 請問要加哪個參數?
求解答,謝謝!

# 中文UI界面翻译插件（可选）
!git clone https://github.com/benlisquare/stable-diffusion-webui-localization-zh_TW localization-zh_TW

#启动程序
%cd /kaggle/working/stable-diffusion-webui
!COMMANDLINE_ARGS="--share --xformers --deepdanbooru --lowram --disable-safe-unpickle  --disable-nan-check" REQS_FILE="requirements.txt" /opt/conda/envs/sdwebui/bin/python3 launch.py

**Comment by harukaxxxx** [comment]
這部分可能要詢問提供 kaggle 版本的開發者，這邊只有做正體中文本地化內容而已😌

**Comment by seq2193** [comment]
沒關係,  謝謝!
