### ISSUE TITLE
因第838行上面的json物件沒有逗點導致插件不能執行

### ISSUE THREAD

**Issue by leo0215** [benlisquare/stable-diffusion-webui-localization-zh_TW#4]
![image](https://user-images.githubusercontent.com/37405572/204313525-3a900839-2462-4c9c-ab76-9714be08ea07.png)

**Comment by benlisquare** [comment]
commit了 145c287efb706d460669f09813c754f0334cc1d2，多謝。merge時沒有注意到，很抱歉。
