### ISSUE TITLE
「蒙版」是中國用語

### ISSUE THREAD

**Issue by DonkeyBear** [benlisquare/stable-diffusion-webui-localization-zh_TW#9]
雖然有少數正體中文使用者會把 `mask` 譯為 `蒙版`，但是在台灣最早的正統翻譯應為 `遮色片`，供參考。

**Comment by harukaxxxx** [comment]
我這邊的fork是改成遮罩，來源是AdobePhotoshop，蒙住也改成遮著了

**Comment by benlisquare** [comment]
harukaxxxx的PR已經解決了mask的翻譯問題，多感謝兩位。
